apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mslu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mslu
    app.kubernetes.io/part-of: ci1t-43256-0098-app
  name: devfile-sample-mslu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mslu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mslu
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0098-tenant/ci1t-43256-0098-app/devfile-sample-mslu@sha256:ba82289a6ce4a14450eea3d891e6b31a70bd57191b3a7ab440f11ae11ed1fdeb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
